import './globals.css'
import Navigation from './navigation'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col h-screen bg-white">
          <main className="flex-grow overflow-y-auto">
            {children}
          </main>
          
          <Navigation />
        </div>
      </body>
    </html>
  )
}
